### ISSUE TITLE
Java used fileDialog for swing 

### ISSUE THREAD

**Issue by hteste** [JetBrains/jcef#20]
Error Info:
java.lang.UnsatisfiedLinkError: org.cef.callback.CefFileDialogCallback_N.N_Continue(JLjava/util/Vector;)V

I have tested all versions with this issue and have learned that only this method cannot be used
Addition:
N_Cancel method is Normal

**Comment by hteste** [comment]
source view:
 private final native void N_Continue(long self, Vector<String> filePaths);

parameters error?

**Comment by ujpv** [comment]
Hi @hteste, some time ago I did some work using `CefFileDialog`. It worked.
may you pls give more details(e.g. OS, JBR version) and share the way to reproduce?

Probably you could use this template to describe the bug(I've just added to this repo as default template).
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots  to help explain your problem.

**Version and environment:**
 - OS: [put here the OS name and version(e.g. macOS 13.4.1 , Ubuntu 22.10, Windows 11)]
 - JetBrains Runtime version: [example 17.0.8+7-b1000.22 aarch64. In a JetBrains IDEs it can be copied from `About IntelliJ IDEA`, `About Clion` etc.] 
- CPU: [put here CPU architecture like arm64, M1, M2, x86, etc.]
- Is OSR enabled: [Yes/No]
- Additional info: [Anything you think might be important in your environment. For example, in the case of graphics problems, you can tell us the number of monitors you are using, their resolutions and scaling factors]

**Additional context**
Add any other context about the problem here.

**Comment by ujpv** [comment]
There may have been misalignment between the versions.
I see that this signature appeared after starting with version 104.

Need more info about the affected version. Is there something special in the environment?

**Comment by kpeterbauer** [comment]
I do not use the JetBrains fork, but the same problems appears when using the original JCEF (binaries from https://github.com/jcefmaven/jcefmaven).

The old signature without int-parameter "selectedAcceptFilter" (both in CefDialogHandler and Callback) is still present in 104.4.23, and there it works. The new signature does not work and throws the UnsatisfiedLinkError (tested with 104.4.23 and 116.0.19.1).

**Comment by ujpv** [comment]
@kpeterbauer that means that this bug is not to this project.
It's better to file a bug for 
https://github.com/jcefmaven/jcefmaven
or 
https://github.com/chromiumembedded/java-cef

jcefmaven project doesn't use our build.
