### ISSUE TITLE
I am encountering this error when opening a webpage. Google Chrome and Microsoft Edge are both working fine. Please fix this bug officially.

### ISSUE THREAD

**Issue by hteste** [JetBrains/jcef#22]
I am encountering this error when opening a webpage. Google Chrome and Microsoft Edge are both working fine. Please fix this bug officially.
Error:
Application error: a client-side exception has occurred (see the browser console for more information).
[0222/184117.656:INFO:CONSOLE(1)] "Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Brel%2C%20href%2C%20precedence%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.",

**Comment by ujpv** [comment]
Unfortunately this bug report doesn't have enough info to reproduce it.
Could you pls feel out this form
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen and what happened instead.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version and environment:**
 - OS: [put here the OS name and version(e.g. macOS 13.4.1 , Ubuntu 22.10, Windows 11)]
 - JetBrains Runtime version: [example 17.0.8+7-b1000.22 aarch64. In a JetBrains IDEs it can be copied from `About IntelliJ IDEA`, `About Clion` etc.] 
- CPU: [put here CPU architecture like arm64, M1, M2, x86, etc.]
- JCEF Version: [e.g. 87476e9]
- CEF Version: [e.g. 110.0.25]
- Is OSR enabled: [Yes/No]
- Additional info: [Anything you think might be important in your environment. For example, in the case of graphics problems, you can tell us the number of monitors you are using, their resolutions and scaling factors]

**Additional context**
Does the problem reproduce with the JCEF simple or detailed sample application at the same version?

Does the problem reproduce with the CEF cefclient or cefsimple sample application at the same version?

Does the problem reproduce with Google Chrome at the same version?

Add any other context about the problem here.
