### ISSUE TITLE
ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

### ISSUE THREAD

**Issue by yqsstudy** [JetBrains/jcef#24]
Our System：centOS7.6  aarch64
see the log：

[0325/214524.866040:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[0325/214525.511311:INFO:render_frame_host_impl.cc(11654)] RenderFrameHostImpl::MaybeGenerateCrashReport url = , status = 3, exit_code = 133
[0325/214526.726842:WARNING:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[0325/214526.729810:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

**Comment by ujpv** [comment]
Now I can only suggest to disable GPU `--disable-gpu` to workaround the problem. Does it help?
1. Are you able to run the most recent chrome on your system?

2. Is it a bug for 
- https://github.com/JetBrains/jcef (this project. JCEF distributed as part of JetBrainRuntime). If so could you pls feel out the suggest bug formular.
- https://github.com/chromiumembedded/java-cef. If so pls file an issue to this project.
- https://github.com/chromiumembedded/cef/ (native cef library). If so pls file an issue to this project.

**Comment by ujpv** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen and what happened instead.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Version and environment:**
 - OS: [put here the OS name and version(e.g. macOS 13.4.1 , Ubuntu 22.10, Windows 11)]
 - JetBrains Runtime version: [example 17.0.8+7-b1000.22 aarch64. In a JetBrains IDEs it can be copied from `About IntelliJ IDEA`, `About Clion` etc.] 
- CPU: [put here CPU architecture like arm64, M1, M2, x86, etc.]
- JCEF Version: [e.g. 87476e9]
- CEF Version: [e.g. 110.0.25]
- Is OSR enabled: [Yes/No]
- Additional info: [Anything you think might be important in your environment. For example, in the case of graphics problems, you can tell us the number of monitors you are using, their resolutions and scaling factors]

**Additional context**
Does the problem reproduce with the JCEF simple or detailed sample application at the same version?

Does the problem reproduce with the CEF cefclient or cefsimple sample application at the same version?

Does the problem reproduce with Google Chrome at the same version?

Add any other context about the problem here.

**Comment by yqsstudy** [comment]
Thanks for your suggestion, but I have tried this method, it has no effect.

**Comment by yqsstudy** [comment]
I've set ide.browser.jcef.gpu.disable=true to disable the GPU, but it still gives me this error.

**Comment by ujpv** [comment]
Thank you for the bug report.
Corresponding ticket in JB bag tracker.
https://youtrack.jetbrains.com/issue/JBR-6898

**Comment by ujpv** [comment]
centos 7 is out of support now.
